services:
  prometheus:
    image: prom/prometheus
    container_name: devops-lab-prometheus
    ports:
      - 9090:9090
  # grafana:
  #   image: grafana
  #   container_name: devops-lab-grafana
  # jenkins:
  #   image: jenkins
